[build]
  publish = "build"  # This is where your build output directory is
  command = "npm run build"  # The build command for your project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
